---
name: VOPRF-TS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testing:
    name: Testing on Node v${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 16]
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Setting up Node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
