name: Release

on:
    release:
        types:
            - published

permissions:
    contents: read
    id-token: write # Required for OIDC token used by npm trusted publishers

jobs:
    release:
        if: ${{ github.repository_owner == 'cloudflare' }}
        name: Publishing to npmjs registry
        runs-on: ubuntu-latest
        steps:
            - name: Checking out
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Use Node.js v20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'
                  cache: 'npm'

            - name: Install NPM dependencies
              run: npm ci

            - name: Check build
              run: npm run build

            - name: Publish to npmjs
              run: npm publish --access public
